### ISSUE TITLE
User UID isn't being unique

### ISSUE THREAD

**Issue by rockcesar** [pi-apps/pi-platform-docs#112]
user_uid isn't being unique. I had the same user pi code, for two user_uid.

Sadly, I deleted one of the registers. It happened because I had an issue an exception in the code, and maybe that was what triggered that behavior in Pi Platform. But I think when you in Pi Platform, pair the Pi Code with User UID, it won't happen again.

**Comment by jabigueroromar** [comment]
user_uid isn't being unique. I had the same user code, for two user_uid.

Sadly, I deleted one of the registers. It happened because I had an issue
an exception in the code, and maybe that was what triggered that behavior
in Pi Platform. But I think when you in Pi Platform, pair the Pi Code with
User UID, it won't happen again


what is the meaning of this

**Comment by rockcesar** [comment]
I register all the transactions and the logged user in my platform, and
noticed two user_uid for the same Pi Code.

**Comment by rockcesar** [comment]
Check this file where appears the same pi code for two different User UID.

**Comment by rockcesar** [comment]
Ok, done, I saw it. UID isn't unique. Thanks.

uid

An app-local identifier for the user. This is specific to this user, and this app. It will change if the user revokes the permissions they granted to your app.
