### ISSUE TITLE
Pi Network Apps Platform Developer Sandbox | Question

### ISSUE THREAD

**Issue by Sten435** [pi-apps/pi-platform-docs#12]
Hey,

Is the Pi Network Apps Platform Developer Sandbox still available?
Yesterday I created a link to test my app in the developer sandbox, but the text is in Chinese, and I have no idea what it says.
I also don't know what I can do in this sandbox sins I can't navigate to URLs.

Could i get some more information about how to use the sandbox?

Greetings
Stan P
<img width="1440" alt="Schermafbeelding 2021-06-29 om 18 53 45" src="https://user-images.githubusercontent.com/44066744/123837603-56db1c80-d90b-11eb-8fe4-86383d2d2b88.png">

**Comment by Yousifxoxo** [comment]
Hah

**Comment by Saiful79NZ** [comment]
Yes still going on,quickly get in and set your app to your refferal language

**Comment by Sten435** [comment]
@Saiful79NZ How do i do that ?

**Comment by aurelienshz** [comment]
Hi there! Thanks for opening the issue. As mentioned [here](https://github.com/pi-apps/pi-platform-docs/issues/11#issuecomment-870640732), the sandbox was released about a year ago, and it was designed to support development of apps using SDK/API v1, which are now both deprecated for new apps. We unfortunately don't have a sandbox environment for SDK/API v2 at the moment (which is why the sandbox is no longer accessible from the home page of developers.minepi.com).

However, given that this is the most frequent request we've been getting, we're working on enabling developers to work on their Pi apps without having to jump through a bunch of hoops to load their `localhost` app in the Pi Browser. I'll close this issue, but let's keep #11 open and host the main conversation on this topic over there.

**Comment by Yousifxoxo** [comment]
Hey

**Comment by Adiza888** [comment]
#27
