### ISSUE TITLE
Detect HTTP and change it by HTTPS in Pi Browser

### ISSUE THREAD

**Issue by rockcesar** [pi-apps/pi-platform-docs#144]
Pi Browser isn't redirecting from http to https, which in Firefox you can do it. Example, this link:

http://minepi.com

In a normal browser, it will redirect to https, but in Pi Browser, can't load the page.

**Comment by rockcesar** [comment]
![Screenshot_20220429-044026_Pi Browser](https://user-images.githubusercontent.com/5984401/165912649-de66e795-63fc-49b6-a48f-aa97e247de8f.jpg)

**Comment by hklee93** [comment]
Redirection is handled on the server side, not by the browser. Not sure why the screenshot failed to load http://minepi.com, but it should automatically open https://minepi.com because we are handling it. Let us know if you have another issue. Thanks.

**Comment by rockcesar** [comment]
Try to access.

https://user-images.githubusercontent.com/5984401/182329923-f774c90f-5c97-4b6c-968f-aea5372a5c55.mp4

**Comment by hklee93** [comment]
Hmm, that's strange. It works fine on my end because as I mentioned, the redirection is only done by the server side. I can try to escalate this issue, but if you're referring the redirection for your app url, it should be done on your side.

https://user-images.githubusercontent.com/17398672/182353017-a73bd5ff-9dc4-4f51-bac9-418124625767.MP4

**Comment by rockcesar** [comment]
Yes, I'm doing the redirection on my server side, but my Pi Browser isn't recognizing. Normal Firefox browser does recognize it. I'm using Android 11.

You can try my App: https://latin-chain.com
