### ISSUE TITLE
Having an issue with PI and bubble.io playforms

### ISSUE THREAD

**Issue by nishanshashintha1996** [pi-apps/pi-platform-docs#205]
Hi team, I'm Nishan Shashintha. I have created an HTML file with your PI SDK integration and it is working fine. Then I integrated that code with the bubble.io platform.. But it is returning the ‘cannot create a payment without “payments“ scope’ error. Also, sandbox mode is always false. Do you guys have any suggestions or solutions for me? Thanks

**Comment by Ray0light** [comment]
Im needing clarification on those issues as well

**Comment by harshajayaweeraXHJ** [comment]
Thanks for raising this issue. We are having trouble deploying this app due to this issue. We have already developed the integrations but this issue is breaking our production deployment. Prompt solution for this would be greatly appreciated. It seems like some apps inside the Iframe cannot communicate with the IFrame host successfully for whatever reason

**Comment by liemnguyen1978** [comment]
First of all I want to send you my sincerest apologies and then I ask for
your forgiveness for this inconvenience. Maybe due to some problem causing
misunderstanding that I signed up but the truth is I didn't register the
integration problem, but I don't know and don't understand the problem you
are talking about. Can you help me to cancel it. And I sincerely thank you
for helping me during this time. Wish you always meet the best things in
life. Dear !

Vào 20:39, CN, 14 Th8, 2022 harshajayaweeraXHJ ***@***.***>
đã viết:

**Comment by hklee93** [comment]
Hi, @nishanshashintha1996 Thanks for reaching out to us. Are you saying you're getting that error even when you're requesting the "payments" as one of your scopes?

**Comment by nishanshashintha1996** [comment]
Hi, @hklee93 Thanks for the response. Here I have attached an explanation video clip and all the app URLs.  
Basically, I'm going to develop a plugin for the bubble.io platform with PI Network integration. For that, I have developed a simple Js app with the PI integration and hosted that on  Namecheap shared hosting. That works fine. Then I integrated the same app on the bobble platform as a plugin. That is not working. It's returning Can not create a payment without "payments" scope. But I have initialized the payment scope. And also the sandbox mode is always false. 

Thank you. Looking forward to hearing from you. 

Explanation video - https://www.loom.com/share/c0373d66a7194416902db579dca86787
bubble application - https://sandbox.minepi.com/app/bubbleplugin
Js application - https://sandbox.minepi.com/app/lkloop-c645a3ed5ad9dffc

bubble.io platform - https://bubble.io/

**Comment by harshajayaweeraXHJ** [comment]
@hklee93  Any update on this please

**Comment by hklee93** [comment]
Sorry, I'm not really familiar with bubble.io you're referring to. But from the vide you posted, it looks like the sandbox mode is false, but you're running using the sandbox url. Can you make sure you can initialize the sdk correctly?

**Comment by nishanshashintha1996** [comment]
Yeh. I have checked it a couple of times. But seems all are implemented correctly.

**Comment by harshajayaweeraXHJ** [comment]
@hklee93 To add @nishanshashintha1996's comment, Same exact code works when we did it with pure javascript html static page on our hosting. But when we load same code and SDK with bubble website builder it doesn't work (What we noticed was sandbox doesn't become true). bubble is also JS and CSS at the end. so it should work. From that it seems there is some communication issue between Iframe and sandbox environment when using `postMessage` to pass data. We can't debug anything else from our side as we don't have any access to sandbox environment.

Can you also try the shared examples (bubble and simple static page) with sandbox environment in your browser and see the difference. You don't need any bubble knowledge for this

Thanks
