### ISSUE TITLE
Pi.createPayment() does not check balance

### ISSUE THREAD

**Issue by dannybutterfield1880** [pi-apps/pi-platform-docs#41]
I've just tried to make a ridiculous payment for 999999999 pi and it worked? I had 130 ish test-pi so I would guess this transaction should fail?

![IMG_20210703_024803.jpg](https://user-images.githubusercontent.com/62266392/124339864-2b755d80-dba9-11eb-8818-b48e8c6fb279.jpg)

![IMG_20210703_024829.jpg](https://user-images.githubusercontent.com/62266392/124339871-303a1180-dba9-11eb-890a-190183b9b143.jpg)

**Comment by vcyk** [comment]
Good test !!

**Comment by teslaproof** [comment]
Shoot me whoop whoop

**Comment by teslaproof** [comment]
Awesome sauce

**Comment by B-Derouet** [comment]
This is completely normal. In fact, in your test, the donor's address is the same as the receiver's, so the transaction is always successful because it's considered that you have the money that you give to yourself, so the transaction doesn't change anything, so it's not an error. If the addresses are different, the transaction will not be completed if you don't have the amount you are giving (you can test with the demo app at `demo.pi` on Pi Browser.

**Comment by dannybutterfield1880** [comment]
@B-Derouet I did think it may be because it's from me to me. Thank you for the response that clears things up. 👍
