### ISSUE TITLE
invalid_amount - Amount can't have more than 7th decimal places.

### ISSUE THREAD

**Issue by dannybutterfield1880** [pi-apps/pi-platform-docs#77]
![image](https://user-images.githubusercontent.com/62266392/127384371-5a430755-4482-431c-9d66-282a719c213e.png)

![image](https://user-images.githubusercontent.com/62266392/127384525-650493ab-4a72-4b69-90c3-c48b239b795f.png)
 
As you can see in the post request I am sending 1.14. This same code was working earlier.

**Comment by B-Derouet** [comment]
The problem comes from Floating Point Math (FPM). Computers can only natively store integers, so they need some way of representing decimal numbers. This representation isn't perfectly accurate. When you have a base 10 system, it can only express fractions that use a prime factor of the base. The prime factors of 10 are 2 and 5. So 1/2, 1/4, 1/5, 1/8, and 1/10 can all be expressed cleanly because the denominators all use prime factors of 10. In contrast, 1/3, 1/6, 1/7 and 1/9 are all repeating decimals because their denominators use a prime factor of 3 or 7.

In binary (or base 2), the only prime factor is 2, so you can only cleanly express fractions whose denominator has only 2 as a prime factor. In binary, 1/2, 1/4, 1/8 would all be expressed cleanly as decimals, while 1/5 or 1/10 would be repeating decimals. When you perform math on these repeating decimals, you end up with leftovers which carry over when you convert the computer’s base 2 (binary) number into a more human-readable base-10 representation.

The problem seams to occur in the Pi Network Platform API backend (when it computes the amount of the transaction and the transaction fee, if both amounts are floats, then there will be FPM, which can result in a float with a number of digits behind the comma higher than 7 (the maximum accepted by Stellar).

One of the most famous examples is this code:
`0.1 + 0.2 != 0.3` (because, with FPM, `0.1 + 0.2 == 0.30000000000000004`)

More info here: https://0.30000000000000004.com/

**Comment by dannybutterfield1880** [comment]
@B-Derouet thank you for the explanation, that makes complete sense. 

I tried with a different amount and it works fine. This is definitely something that other people are going to face especially with multi vendor stores where the site owner cannot always manage the price of products.

**Comment by Sten435** [comment]
I had the same issue with my app, but i just made sure the amount cant pass 7 digits. But when you have a store its a big harder you cant say to peaple that they can buy a product becuse they have an amount over 7 digits.

**Comment by hklee93** [comment]
Ah I'll look into this issue. Thanks for letting me know.

**Comment by Kittenmoon21** [comment]
If it can't have over a 7th decimal couldn't you just round that off and to it too small to trade bin and collect them in a bulk after so many trades and convert them

**Comment by Sten435** [comment]
> If it can't have over a 7th decimal couldn't you just round that off and to it too small to trade bin and collect them in a bulk after so many trades and convert them

What if you want a value over 7digits without any commas, for ex: "100000000€" its unlikely for anywane to ever buy somting from this value... But you get get what i mean.

**Comment by hklee93** [comment]
Sorry that it took a while. The fix is on the way. It's not deployed yet, but it will be shipped within a few days. I'll close the issue for now. Feel free to open again if it still is an issue.
